#Configuración específica para el proyecto user en WebService
compilarUser:
  image: maven:3.9.3-eclipse-temurin-17
  stage: compilar
  script:
    - echo "Compilando el backend - WebService/user"
    - cd WebService/user
    - mvn clean install -DskipTests
    - cd ../../
  artifacts:
    paths:
      - WebService/user/target/user-*.jar
  allow_failure: false

pruebasAutomaticasUser:
  stage: pruebasAutomaticas
  image: maven:3.9.3-eclipse-temurin-17
  script:
    - echo "Ejecutando pruebas automáticas del backend - WebService/user"
    - cd WebService/user
    - mvn test
    - cd ../../
  allow_failure: true

sonarUser:
  stage: sonarQube
  image: maven:3.9.3-eclipse-temurin-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  script:
    - echo "Ejecutando SonarQube para photofilm4you/WebService/user"
    - cd WebService/user
    - |
      mvn clean verify sonar:sonar -Dsonar.coverage.exclusions="**/generated-sources/**,**/target/**" $CUSTOM_PROPERTIES_MVN_USER $CUSTOM_PROPERTIES_SONAR_QUALITYGATE -Dsonar.projectName="PDS_2023_B5_WebService_user" -Dsonar.projectKey="PDS_2023_B5_WebService_user"
    - cd ../../
  allow_failure: true
